// Front routing Worker — the ADR-0004 §3 composition, this slice.
//
// Assets-first: requests matching this Worker's own static assets (the home
// surface at /, ADR-0007) never reach this script. Everything else dispatches
// by path prefix over a service binding, forwarding the ORIGINAL request
// untouched — variant assets are nested under /{variant}/ (the documented
// "serving a subdirectory" shape), so no path rewriting happens and
// asset-layer redirects stay correct (spike-verified).
//
// /api/* and /assets/* dispatch to the edge Worker (the ADR-0002 §8 data
// plane, issue #4). Variant HTML gets the switcher/HUD chrome injected into
// the documented `div#pm-chrome-slot` via HTMLRewriter (ADR-0004 §7, spike
// hardening 2) — HTML only, content-type guarded; everything else passes
// through byte-identical. The /_pm/* instrumentation path (chrome.css +
// the pinned measurement bundle + the published lab receipts and bundles
// under /_pm/lab/) is served assets-first from this Worker's own dist, so
// instrumentation bytes stay strippable by known path (ADR-0001 §6). The
// methodology page (/methodology/, ADR-0001 §9) rides the same assets-first
// path as home — static singletons, no injected chrome.
//
// Every response this script returns — proxied or its own — leaves through
// the security-header floor (security-floor.js; 2026-08-29 audit priority 4,
// landed 2026-09-18): nosniff, a referrer policy and a frame policy,
// identical for every variant, so the floor is part of the held-constant
// transport (ADR-0004 §3) and never a per-variant variable. The assets-first
// paths get the same three headers from dist/_headers, which build.mjs
// writes from the same module.

import { renderChrome } from "@pm/switcher";
import { VARIANT_PREFIXES, getProfile, PROFILES } from "@pm/measurement";
import { withSecurityFloor } from "./security-floor.js";
// The published-runs bundles (ADR-0008 §3: the front build hands the bundle
// to renderChrome — nothing fetches). GENERATED by build.mjs from the
// labBundle-flagged surfaces in SURFACE_CONTROLS, with each bundle imported
// from the very file served at /_pm/lab/{surface}.json — so the embedded
// object and the served artifact are one thing, and setting the flag is the
// WHOLE registration. A hand-maintained list here could go stale against the
// registry without any guard noticing (verify-slice, unanimous across four
// lenses); generating it removes the class instead of guarding it.
import { LAB_BUNDLES } from "../generated/lab-bundles.js";

// Checked as JS (tsconfig.json `checkJs`; ADR-0004 addendum, 2026-09-25):
// `Env` is wrangler's generated binding interface (cloudflare-env.d.ts — the
// ten service bindings), the chrome's contract is @pm/switcher's, and the
// generated bundle module is JSON, so its literal types are the served
// artifact's; the switcher's SurfaceLabBundle is what they MEAN, stated
// once here at the consumer.
/** @typedef {import("@pm/switcher").SurfaceLabBundle} SurfaceLabBundle */
/** @type {Readonly<Record<string, Readonly<Record<string, SurfaceLabBundle>>>>} */
const LAB = /** @type {any} */ (LAB_BUNDLES);

/** The per-surface, per-profile published bundle for this request, or
 *  undefined (the chrome renders its designed empty states). Profile
 *  resolution mirrors the chrome's own reading-section selector EXACTLY
 *  (getProfile(param) ?? default) — a mismatch would render one profile's
 *  numbers under another profile's selected cell. Object.hasOwn throughout:
 *  surface and profile are client-controlled (the repo's recurring
 *  prototype-key class). */
/** @param {string} surface @param {string} search @returns {SurfaceLabBundle | undefined} */
function labFor(surface, search) {
  const bundles = Object.hasOwn(LAB, surface) ? LAB[surface] : undefined;
  if (!bundles) return undefined;
  const requested = new URLSearchParams(search).get("profile") ?? "";
  const resolved = (getProfile(requested) ?? PROFILES["avg-broadband-desktop"]).id;
  return Object.hasOwn(bundles, resolved) ? bundles[resolved] : undefined;
}

// Prefix → service binding, DERIVED from the beacon roster's variant list
// (@pm/measurement VARIANT_PREFIXES; security floor, 2026-09-18). The edge
// collector accepts a `variant` tag iff it is on that list, and the chrome's
// tag is the prefix this table dispatches — deriving the table from the
// roster means a variant this Worker serves is a variant whose RUM the
// collector keeps, by construction, with no second list to go stale. Binding
// names are the prefix upper-cased with `-` → `_` (wrangler.jsonc `services`);
// a prefix with no binding 502s on dispatch, which the origin suite's
// dispatch legs see.
// The fenced frontier exhibit (remix3, editorial-build slice F) is on the
// list like any variant: dispatched and chrome-injected — the fence excludes
// NUMBERS, not the composed origin's mechanics (ADR-0004 second addendum).
// The bench runner refuses /remix3/* targets; the switcher renders it as a
// fenced cell, never a reading-table column.
const VARIANTS = Object.fromEntries(
  VARIANT_PREFIXES.map((prefix) => [prefix, prefix.toUpperCase().replaceAll("-", "_")]),
);

// Sibling planes (ADR-0009 §1): same prefix dispatch, but responses pass
// through byte-identical like EDGE — no chrome, no HUD, no receipts. The
// blog is outside every measurement fence.
/** @type {Readonly<Record<string, string>>} */
const SIBLINGS = {
  blog: "BLOG",
};

// Structured JSON logs (Workers Logs ingests console output; PRD story 42).
/** @param {"info" | "error"} level @param {string} event @param {Record<string, unknown>} fields */
function log(level, event, fields) {
  const line = JSON.stringify({ level, worker: "pm-front", event, ...fields });
  if (level === "error") console.error(line);
  else console.log(line);
}

const front = {
  // Dispatch + chrome injection. Returns the response WITHOUT the security
  // floor; the exported `fetch` below is the one place it is applied.
  /**
   * @param {Request<unknown, IncomingRequestCfProperties>} request
   * @param {Env} env
   * @returns {Promise<Response>}
   */
  async route(request, env) {
    const url = new URL(request.url);
    const prefix = url.pathname.split("/")[1] ?? "";

    // The data plane (ADR-0002 §8): trays + beacons under /api/*, the frozen
    // self-hosted images under /assets/* — both served by the edge Worker.
    const bindingName =
      prefix === "api" || prefix === "assets"
        ? "EDGE"
        : Object.hasOwn(SIBLINGS, prefix)
          ? SIBLINGS[prefix]
          : Object.hasOwn(VARIANTS, prefix) // bare lookups resolve prototype keys
            ? VARIANTS[prefix]              // ("constructor" 502'd instead of 404)
            : undefined;
    const variant = bindingName === "EDGE" ? "edge" : prefix;

    if (!bindingName) {
      log("info", "unknown-prefix", { path: url.pathname });
      return new Response("not found\n", { status: 404 });
    }

    try {
      // Every name the three tables produce IS a binding: the dispatch
      // table is derived from the roster and pinned to wrangler.jsonc's
      // `services` by test/floor-and-dispatch.test.js, and `Env` is
      // generated from that same file — so the cast states what the test
      // proves, and a prefix with no binding still 502s below.
      const upstream = await env[/** @type {keyof Env} */ (bindingName)].fetch(request);
      log("info", "dispatch", {
        variant,
        path: url.pathname,
        status: upstream.status,
      });

      // Chrome injection: variant HTML only. The edge Worker's JSON/images,
      // sibling planes (the blog), and every non-HTML response pass through
      // byte-identical — the content-type guard IS the non-HTML guarantee.
      const contentType = upstream.headers.get("content-type") ?? "";
      if (
        bindingName === "EDGE" ||
        bindingName === "BLOG" ||
        !contentType.includes("text/html")
      ) {
        return upstream;
      }

      // remix3's frame PARTIALS are HTML that is not a page (editorial-build
      // slice F): server-rendered fragments the exhibit's frames reload over
      // the wire. The slot contract is a PAGE contract — injecting chrome
      // into a fragment or error-logging its designed slotlessness would
      // both be wrong — so partials pass through byte-identical (the
      // q-data.json precedent from slice D). Deliberately variant-scoped,
      // not a plane-wide "/frames/" convention.
      if (variant === "remix3" && url.pathname.startsWith("/remix3/editorial/frames/")) {
        return upstream;
      }
      // The generalization that exemption asked for (PLP data plane,
      // 2026-09-04): any variant may serve HTML that is not a page, and the
      // response DECLARES it. The htmx PLP's boosted swaps (ADR-0005 §1) set
      // `x-pm-partial: 1` on every fragment response; until this line landed
      // the composed origin logged `chrome-slot-count` as an ERROR on every
      // page-flip against a Worker behaving correctly (PLP handoff §6.1).
      // Header, not `HX-Request`: htmx's history-restore re-fetch also
      // carries HX-Request and legitimately wants the WHOLE document.
      if (upstream.headers.get("x-pm-partial")) {
        return upstream;
      }

      const surface = url.pathname.split("/")[2] ?? "";
      const chrome = renderChrome({
        variant,
        surface,
        pathname: url.pathname,
        search: url.search,
        // Where this response was served from — the beacon's location tag.
        // cf is absent in local dev.
        location: request.cf?.colo ?? "local",
        // Published readings, when this surface has them under the selected
        // profile. A fenced exhibit's page passes the same bundle: its
        // reading table reads the BENCHMARKED variants (ADR-0008 §3).
        lab: labFor(surface, url.search),
      });
      // Slot cardinality is a page CONTRACT (exactly one): zero slots ships
      // an unmeasured, switcher-less page; two double-inject the measurement
      // script and double-count RUM. The stream has already left when the
      // count is known, so the violation is logged, not blocked — Workers
      // Logs makes it observable (verified failure modes in workerd).
      let slotCount = 0;
      return new HTMLRewriter()
        // chrome.css rides in <head> (surface-design session): an in-body
        // stylesheet at the top of every measured page either blocks paint of
        // everything after it or flashes an unstyled strip — head placement
        // kills both, and the preload starts the instrument mono without a
        // late 3-hop chain. Both files live on /_pm/* (stripped from measured
        // KB by known path, ADR-0001 §6).
        .on("head", {
          element(el) {
            el.append(
              `<link rel="preload" href="/_pm/fonts/PMInstrumentMono.var.woff2" as="font" type="font/woff2" crossorigin>` +
                `<link rel="stylesheet" href="/_pm/chrome.css">`,
              { html: true },
            );
          },
        })
        .on("div#pm-chrome-slot", {
          element(el) {
            slotCount += 1;
            el.setInnerContent(chrome, { html: true });
          },
        })
        .onDocument({
          end() {
            if (slotCount !== 1) {
              log("error", "chrome-slot-count", {
                variant,
                path: url.pathname,
                count: slotCount,
              });
            }
          },
        })
        .transform(upstream);
    } catch (err) {
      // Generic message out; details stay server-side (security.md: never
      // present raw exceptions to the user).
      log("error", "upstream-failure", {
        variant,
        path: url.pathname,
        message: err instanceof Error ? err.message : String(err),
        stack: err instanceof Error ? err.stack : undefined,
      });
      return new Response("upstream unavailable\n", { status: 502 });
    }
  },
};

export default {
  // EVERY response leaves through the security floor — proxied pages,
  // fragments, JSON, images, the blog, and this Worker's own 404 and 502 —
  // so the floor is a property of the seam, not of each return statement
  // (security-floor.js). The assets-first paths never reach this function;
  // dist/_headers carries the same three headers there.
  /** @param {Request<unknown, IncomingRequestCfProperties>} request @param {Env} env */
  async fetch(request, env) {
    return withSecurityFloor(await front.route(request, env));
  },
};
