// The security-header floor (2026-08-29 audit, priority 4; decision map
// `security-floor`; ADR-0004 §3 addendum of 2026-09-18).
//
// Three headers on EVERY response the composed origin serves, identically
// for every variant — the floor is part of the held-constant transport, so it
// can never become a per-variant variable and it cancels in every comparison:
//   x-content-type-options: nosniff        — no MIME sniffing of served bytes
//   referrer-policy: strict-origin-when-cross-origin — the blog's value (ADR-0009)
//   x-frame-options: DENY                  — nothing legitimately embeds the store
//
// ONE definition, two mechanisms, because the front has two serving paths:
//  - `withSecurityFloor` wraps every Response the SCRIPT returns — proxied
//    variant pages and fragments, the data plane's JSON and images, the blog,
//    the front's own 404/502. `new Response(body, response)` is the documented
//    way to get mutable headers on a fetched response ("Alter headers",
//    developers.cloudflare.com/workers/examples/alter-headers/, fetched
//    2026-09-18); `set`, not `append`, so an upstream cannot weaken the floor.
//  - `headersFileText` is written to dist/_headers by build.mjs for the
//    assets-first paths (/, /methodology/, /how-it-was-built/, /_pm/*, /pm/*)
//    that never reach this script. Cloudflare's docs
//    (developers.cloudflare.com/workers/static-assets/headers/, fetched
//    2026-09-18): the file "can go directly into your static assets
//    directory", "will not itself be served as a static asset", and "Custom
//    headers defined in the `_headers` file are not applied to responses
//    generated by your Worker code" — which is why both mechanisms exist.
//
// A Content-Security-Policy is deliberately NOT here. A full CSP is a
// separate decision (recorded in the decision map, not shipped by half):
// qwik and astro emit inline scripts, so a script-src would need
// 'unsafe-inline' or per-response nonces, and nonces would touch the
// byte-identity guards. The origin suite pins the ABSENCE on store pages so a
// half-CSP cannot arrive by accident; the blog keeps its own, stronger set.
//
// Wire cost, so the byte discipline can name it (ADR-0001 addendum U): the
// three lines are 106 bytes uncompressed per response on HTTP/1.1 (measured
// on the local plane, 2026-09-18). Under HTTP/2 HPACK none of the three is in
// the static table (RFC 7541 Appendix A, 61 entries), so the first response
// on a connection carries them as Huffman literals and every later one as a
// 1-byte dynamic-table index each; under HTTP/3 QPACK two of the three have
// static entries (RFC 9204 Appendix A: `x-content-type-options: nosniff` at
// 61, `x-frame-options: deny` at 97). None of it reaches a published byte
// cell: Resource Timing's `transferSize` replaces the header component with
// a constant 300 octets by spec, and Chromium implements exactly that
// (`kHeaderSize = 300`), so the ruler cannot see response headers at all.
// Identical on every variant regardless, so it cancels in every comparison.

/** Header name → value. Lower-case names: that is how HTTP/2 and HTTP/3
 *  carry them, and how the Headers API reads them back. */
export const SECURITY_FLOOR = Object.freeze({
  "x-content-type-options": "nosniff",
  "referrer-policy": "strict-origin-when-cross-origin",
  "x-frame-options": "DENY",
});

/** A copy of `response` carrying the floor. The body streams through; a
 *  null body (204/304/HEAD) stays null.
 *  @param {Response} response @returns {Response} */
export function withSecurityFloor(response) {
  const floored = new Response(response.body, response);
  for (const [name, value] of Object.entries(SECURITY_FLOOR)) {
    floored.headers.set(name, value);
  }
  return floored;
}

/** The `_headers` file for the assets-first paths: one rule, every asset. */
export function headersFileText() {
  return [
    "/*",
    ...Object.entries(SECURITY_FLOOR).map(([name, value]) => `  ${name}: ${value}`),
    "",
  ].join("\n");
}
